style: retab shell scripts
Signed-off-by: WANG Xuerui <wangxuerui@iscas.ac.cn>

diff --git a/ruyi-build-ctng b/ruyi-build-ctng
--- a/ruyi-build-ctng
+++ b/ruyi-build-ctng
@@ -6,41 +6,41 @@ MY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 source "$MY_DIR"/containers/_image_tag_base.sh
 
 if [[ -z $RUYI_BUILDER_TAG ]]; then
-	RUYI_BUILDER_TAG="$(image_tag_pkgbuilder unified amd64)"
+    RUYI_BUILDER_TAG="$(image_tag_pkgbuilder unified amd64)"
 fi
 
 die() {
-	echo "$@" >&2
-	exit 1
+    echo "$@" >&2
+    exit 1
 }
 
 ensure_dir() {
-	local path="$1"
-	[[ -d "$path" ]] || mkdir "$path"
+    local path="$1"
+    [[ -d "$path" ]] || mkdir "$path"
 }
 
 main() {
-	local config="$1"
+    local config="$1"
 
-	ensure_dir "$MY_DIR/out"
-	ensure_dir "$MY_DIR/prefix"
-	ensure_dir "$MY_DIR/src"
-	ensure_dir "$MY_DIR/work"
+    ensure_dir "$MY_DIR/out"
+    ensure_dir "$MY_DIR/prefix"
+    ensure_dir "$MY_DIR/src"
+    ensure_dir "$MY_DIR/work"
 
-	local docker_args=(
-		--rm
-		-ti
-		-v "$MY_DIR/out":/out
-		-v "$MY_DIR/prefix":/opt/ruyi
-		-v "$MY_DIR/src":/src
-		-v "$MY_DIR/work":/work
-		-v "$MY_DIR/toolchain-patches":/patches:ro
-		-v "$MY_DIR/ruyi-build-ctng-inner":/usr/local/bin/ruyi-build-ctng-inner:ro
-		-v "$(realpath "$config")":/tmp/input.defconfig:ro
-		"${RUYI_BUILDER_TAG}"
-		ruyi-build-ctng-inner /tmp/input.defconfig
-	)
-	docker run "${docker_args[@]}" || die "inner build pass failed"
+    local docker_args=(
+        --rm
+        -ti
+        -v "$MY_DIR/out":/out
+        -v "$MY_DIR/prefix":/opt/ruyi
+        -v "$MY_DIR/src":/src
+        -v "$MY_DIR/work":/work
+        -v "$MY_DIR/toolchain-patches":/patches:ro
+        -v "$MY_DIR/ruyi-build-ctng-inner":/usr/local/bin/ruyi-build-ctng-inner:ro
+        -v "$(realpath "$config")":/tmp/input.defconfig:ro
+        "${RUYI_BUILDER_TAG}"
+        ruyi-build-ctng-inner /tmp/input.defconfig
+    )
+    docker run "${docker_args[@]}" || die "inner build pass failed"
 }
 
 main "$@"
diff --git a/ruyi-build-dynamorio b/ruyi-build-dynamorio
--- a/ruyi-build-dynamorio
+++ b/ruyi-build-dynamorio
@@ -6,35 +6,35 @@ MY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 source "$MY_DIR"/containers/_image_tag_base.sh
 
 if [[ -z $RUYI_BUILDER_TAG ]]; then
-	RUYI_BUILDER_TAG="$(image_tag_pkgbuilder unified amd64)"
+    RUYI_BUILDER_TAG="$(image_tag_pkgbuilder unified amd64)"
 fi
 
 die() {
-	echo "$@" >&2
-	exit 1
+    echo "$@" >&2
+    exit 1
 }
 
 ensure_dir() {
-	local path="$1"
-	[[ -d "$path" ]] || mkdir "$path"
+    local path="$1"
+    [[ -d "$path" ]] || mkdir "$path"
 }
 
 main() {
-	ensure_dir "$MY_DIR/out"
-	ensure_dir "$MY_DIR/work"
+    ensure_dir "$MY_DIR/out"
+    ensure_dir "$MY_DIR/work"
 
-	local docker_args=(
-		--user root  # FIXME: remove after next builder image bump
-		--rm
-		-ti
-		-v "$MY_DIR/out":/out
-		-v "$MY_DIR/work":/work
-		-v "$MY_DIR/ruyi-build-dynamorio-inner":/usr/local/bin/ruyi-build-dynamorio-inner:ro
-		"${RUYI_BUILDER_TAG}"
-		ruyi-build-dynamorio-inner
-		"$@"
-	)
-	docker run "${docker_args[@]}" || die "inner build pass failed"
+    local docker_args=(
+        --user root  # FIXME: remove after next builder image bump
+        --rm
+        -ti
+        -v "$MY_DIR/out":/out
+        -v "$MY_DIR/work":/work
+        -v "$MY_DIR/ruyi-build-dynamorio-inner":/usr/local/bin/ruyi-build-dynamorio-inner:ro
+        "${RUYI_BUILDER_TAG}"
+        ruyi-build-dynamorio-inner
+        "$@"
+    )
+    docker run "${docker_args[@]}" || die "inner build pass failed"
 }
 
 main "$@"
diff --git a/ruyi-build-dynamorio-inner b/ruyi-build-dynamorio-inner
--- a/ruyi-build-dynamorio-inner
+++ b/ruyi-build-dynamorio-inner
@@ -10,11 +10,11 @@ RUYI_DATESTAMP=20240914
 
 case "$ARCH" in
 amd64|arm64|riscv64)
-	;;
+    ;;
 *)
-	echo "invalid ARCH: choices are amd64 (default), arm64 or riscv64" >&2
-	exit 1
-	;;
+    echo "invalid ARCH: choices are amd64 (default), arm64 or riscv64" >&2
+    exit 1
+    ;;
 esac
 
 OUT_P="dynamorio-riscv-$PV-ruyi.$RUYI_DATESTAMP"
diff --git a/ruyi-build-llvm b/ruyi-build-llvm
--- a/ruyi-build-llvm
+++ b/ruyi-build-llvm
@@ -8,53 +8,53 @@ ARCH="${ARCH:-amd64}"
 source "$MY_DIR"/containers/_image_tag_base.sh
 
 if [[ -z $RUYI_BUILDER_TAG ]]; then
-	RUYI_BUILDER_TAG="$(image_tag_pkgbuilder unified amd64)"
+    RUYI_BUILDER_TAG="$(image_tag_pkgbuilder unified amd64)"
 fi
 
 die() {
-	echo "$@" >&2
-	exit 1
+    echo "$@" >&2
+    exit 1
 }
 
 ensure_dir() {
-	local path="$1"
-	[[ -d "$path" ]] || mkdir "$path"
+    local path="$1"
+    [[ -d "$path" ]] || mkdir "$path"
 }
 
 main() {
-	local cfg="$1"
-	local pkg="$2"
+    local cfg="$1"
+    local pkg="$2"
 
-	ensure_dir "$MY_DIR/out"
-	ensure_dir "$MY_DIR/work"
+    ensure_dir "$MY_DIR/out"
+    ensure_dir "$MY_DIR/work"
 
-	# assume /tmp is tmpfs for now
-	TMP_MEM_DIR="$(mktemp -d)"
+    # assume /tmp is tmpfs for now
+    TMP_MEM_DIR="$(mktemp -d)"
 
-	local docker_args=(
-		--rm
-		-ti
-		-v "$MY_DIR/out":/out
-		-v "$MY_DIR/work":/work
-		-v "$MY_DIR/ruyi-build-llvm-inner":/usr/local/bin/ruyi-build-llvm-inner:ro
-		-v "$(realpath "$cfg")":/tmp/config.sh:ro
-		-v "$TMP_MEM_DIR":/tmp/mem
-	)
+    local docker_args=(
+        --rm
+        -ti
+        -v "$MY_DIR/out":/out
+        -v "$MY_DIR/work":/work
+        -v "$MY_DIR/ruyi-build-llvm-inner":/usr/local/bin/ruyi-build-llvm-inner:ro
+        -v "$(realpath "$cfg")":/tmp/config.sh:ro
+        -v "$TMP_MEM_DIR":/tmp/mem
+    )
 
-	if [[ -n $pkg ]]; then
-		docker_args+=(
-			-v "$pkg":/tmp/src.tar.xz:ro
-		)
-	fi
+    if [[ -n $pkg ]]; then
+        docker_args+=(
+            -v "$pkg":/tmp/src.tar.xz:ro
+        )
+    fi
 
-	docker_args+=(
-		"${RUYI_BUILDER_TAG}"
-		ruyi-build-llvm-inner
-		/tmp/config.sh
-		"$ARCH"
-	)
+    docker_args+=(
+        "${RUYI_BUILDER_TAG}"
+        ruyi-build-llvm-inner
+        /tmp/config.sh
+        "$ARCH"
+    )
 
-	docker run "${docker_args[@]}" || die "inner build pass failed"
+    docker run "${docker_args[@]}" || die "inner build pass failed"
 }
 
 main "$@"
